### ISSUE TITLE
os_v3_windsensor.cpp contains the source code for the rain sensor

### ISSUE THREAD

**Issue by karioja** [deberman/OsV3_wind_sensor#1]
The code for the wind sensor is nowhere to be found.

**Comment by deberman** [comment]
I had some sync problems with the desktop app and forgot about it. I can get the correct code uploaded for you when I get home on sunday.

**Comment by deberman** [comment]
Sorry, I messed up the sync when I was working on it and forgot about it. I am away but can get the correct code uploaded on sunday. 
/d

**Comment by deberman** [comment]
Hopefully this is the working version.
